import type {
  BleachMethod,
  DryMethod,
  EvidenceMeta,
  GarmentCareProfile,
  IronMethod,
  TwinState,
  WashMethod,
} from "./types";

const confirmed: EvidenceMeta = {
  provenance: "user-confirmed",
  confidence: 1,
  reviewStatus: "confirmed",
};

const seedProvenance = {
  name: confirmed,
  category: confirmed,
  colour: confirmed,
  material: confirmed,
};

function seedCare(
  wash: WashMethod,
  dry: DryMethod,
  iron: IronMethod,
  bleach: BleachMethod,
  notes: string[],
): GarmentCareProfile {
  return {
    wash: { value: wash, ...confirmed },
    dry: { value: dry, ...confirmed },
    iron: { value: iron, ...confirmed },
    bleach: { value: bleach, ...confirmed },
    notes: { value: notes, ...confirmed },
  };
}

export function createSeedState(): TwinState {
  return {
    garments: {
      "cream-blouse": {
        id: "cream-blouse",
        name: "Cream cotton blouse",
        category: "top",
        colour: "Warm cream",
        material: "82% cotton · 18% modal",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "machine-cold",
          "line-dry-shade",
          "low",
          "do-not-bleach",
          ["Wash with similar light colours"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 0,
        wearPolicy: {
          postWearMode: "wash",
          maxWearsBeforeWash: 1,
          source: "user-confirmed",
        },
      },
      "chocolate-trousers": {
        id: "chocolate-trousers",
        name: "Chocolate wide-leg trousers",
        category: "bottom",
        colour: "Chocolate",
        material: "Cotton-viscose blend",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "machine-cold",
          "line-dry",
          "medium",
          "do-not-bleach",
          ["Turn inside out before washing"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 0,
        wearPolicy: {
          postWearMode: "rewearable",
          maxWearsBeforeWash: 3,
          source: "care-profile",
        },
      },
      "olive-jacket": {
        id: "olive-jacket",
        name: "Olive cropped jacket",
        category: "outerwear",
        colour: "Deep olive",
        material: "Linen-cotton blend",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "hand-wash",
          "line-dry-shade",
          "low",
          "do-not-bleach",
          ["Reshape while damp"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 1,
        wearPolicy: {
          postWearMode: "airing",
          maxWearsBeforeWash: 5,
          source: "care-profile",
        },
      },
      "gold-earrings": {
        id: "gold-earrings",
        name: "Sculpted gold earrings",
        category: "accessory",
        colour: "Gold",
        material: "Gold-plated steel",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "unknown",
          "unknown",
          "unknown",
          "unknown",
          ["Wipe clean; keep dry"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 0,
        wearPolicy: {
          postWearMode: "available",
          maxWearsBeforeWash: 20,
          source: "user-confirmed",
        },
      },
      "black-loafers": {
        id: "black-loafers",
        name: "Black leather loafers",
        category: "shoes",
        colour: "Black",
        material: "Leather upper",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "unknown",
          "unknown",
          "unknown",
          "unknown",
          ["Wipe clean with a soft cloth"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 2,
        wearPolicy: {
          postWearMode: "available",
          maxWearsBeforeWash: 20,
          source: "user-confirmed",
        },
      },
      "ivory-knit": {
        id: "ivory-knit",
        name: "Ivory ribbed knit",
        category: "top",
        colour: "Ivory",
        material: "Viscose-nylon blend",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "hand-wash",
          "flat-dry",
          "low",
          "do-not-bleach",
          ["Do not wring"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 0,
        wearPolicy: {
          postWearMode: "wash",
          maxWearsBeforeWash: 1,
          source: "care-profile",
        },
      },
      "indigo-shirt": {
        id: "indigo-shirt",
        name: "Indigo poplin shirt",
        category: "top",
        colour: "Deep indigo",
        material: "100% cotton poplin",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "machine-cold",
          "line-dry-shade",
          "medium",
          "do-not-bleach",
          ["Wash with similar dark colours"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 0,
        wearPolicy: {
          postWearMode: "rewearable",
          maxWearsBeforeWash: 2,
          source: "user-confirmed",
        },
      },
      "terracotta-skirt": {
        id: "terracotta-skirt",
        name: "Terracotta column skirt",
        category: "bottom",
        colour: "Burnt terracotta",
        material: "Linen-viscose blend",
        imageAssetId: null,
        careLabelAssetId: null,
        provenance: seedProvenance,
        careProfile: seedCare(
          "machine-cold",
          "line-dry-shade",
          "low",
          "do-not-bleach",
          ["Wash with similar colours", "Reshape while damp"],
        ),
        source: "seed",
        state: "available",
        wearsSinceWash: 0,
        wearPolicy: {
          postWearMode: "rewearable",
          maxWearsBeforeWash: 3,
          source: "care-profile",
        },
      },
    },
    outfits: {
      "today-city-calm": {
        id: "today-city-calm",
        name: "City Calm",
        occasion: "Creative workday",
        scheduledFor: "Today",
        garmentIds: [
          "cream-blouse",
          "chocolate-trousers",
          "olive-jacket",
          "gold-earrings",
          "black-loafers",
        ],
        status: "planned",
        personalMatch: 88,
        styleSignals: ["warm-neutral", "structured", "high-waist"],
        source: "seed",
        scheduledAt: "2026-08-14T09:00:00.000+03:00",
        planningContext: null,
        scoreBreakdown: [],
        engineVersion: "seed",
        dependencies: [
          "cream-blouse",
          "chocolate-trousers",
          "olive-jacket",
          "gold-earrings",
          "black-loafers",
        ],
      },
      "friday-rooftop": {
        id: "friday-rooftop",
        name: "Friday Rooftop",
        occasion: "Dinner in Kampala",
        scheduledFor: "Friday · 7:00 PM",
        garmentIds: [
          "cream-blouse",
          "chocolate-trousers",
          "gold-earrings",
          "black-loafers",
        ],
        status: "planned",
        personalMatch: 91,
        styleSignals: ["warm-neutral", "elegant", "high-waist"],
        source: "seed",
        scheduledAt: "2026-08-14T19:00:00.000+03:00",
        planningContext: null,
        scoreBreakdown: [],
        engineVersion: "seed",
        dependencies: [
          "cream-blouse",
          "chocolate-trousers",
          "gold-earrings",
          "black-loafers",
        ],
      },
    },
    feedback: [],
    styleMemory: {
      feedbackCount: 0,
      averageConfidence: null,
      signals: {},
    },
    styleProfile: {
      version: 1,
      heightCm: 168,
      colourRelationship: "warm",
      preferredColours: ["cream", "olive", "chocolate"],
      avoidedColours: [],
      fitPreferences: ["defined-waist", "tailored"],
      comfortPriorities: ["breathable", "easy-movement"],
      styleWords: ["calm", "polished", "textural"],
      updatedAt: null,
    },
    inspirationLooks: {},
  };
}
